### ISSUE TITLE
添加一个手动只抓取标题的，返回这个报错消息

### ISSUE THREAD

**Issue by Corray** [wonderfulsuccess/weixin_crawler#22]
![E041B19B-6046-419f-BDEB-09E878FBDF56](https://user-images.githubusercontent.com/14108310/54658482-8bdf4e80-4b08-11e9-9ba6-78914ee6e912.png)

**Comment by Corray** [comment]
Traceback (most recent call last):
  File ".\main.py", line 7, in <module>
    run_gzh_crawler()
  File "E:\python\weixin_crawler\project\ui\__init__.py", line 22, in run_gzh_crawler
    gc.run()
  File "E:\python\weixin_crawler\project\Application\gzh_crawler\__init__.py", line 184, in run
    from crawler import run_crawl
  File "E:\python\weixin_crawler\project\crawler\__init__.py", line 3, in <module>
    from crawler.crawler.spiders.article_list import ArticleListSpider
  File "E:\python\weixin_crawler\project\crawler\crawler\spiders\article_list.py", line 9, in <module>
    class ArticleListSpider(scrapy.Spider):
  File "E:\python\weixin_crawler\project\crawler\crawler\spiders\article_list.py", line 14, in ArticleListSpider
    wx_num,_,_ = TidyReqData.get_gzh_req_data()
  File "E:\python\weixin_crawler\project\crawler_assist\tidy_req_data.py", line 181, in get_gzh_req_data
    req_data_dict = TidyReqData.tidy()
  File "E:\python\weixin_crawler\project\crawler_assist\tidy_req_data.py", line 121, in tidy
    tidy_req_data = TidyReqData.add_nick_name(tidy_req_data)
  File "E:\python\weixin_crawler\project\crawler_assist\tidy_req_data.py", line 48, in add_nick_name
    ordered_req_dict[key]['nick_name'] = wxuin_nn_dict[key]
KeyError: 'pgv_pvid=9042519537; sd_userid=34921551630270924; sd_cookie_crttime=1551630270924; rewardsn=; devicetype=android-28; lang=zh_CN; version=2700033b'

**Comment by wonderfulsuccess** [comment]
可能是手机操作公众号的步骤有缺漏 建议看看release中wcplus的说明书
