### ISSUE TITLE
运行main.py报错，localhost:5000连不上

### ISSUE THREAD

**Issue by GarbageSal** [wonderfulsuccess/weixin_crawler#23]
运行 `python3 ./main.py` 后出现以下错误：
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zhaohaotian/Desktop/weixin_crawler/project/ui/__init__.py", line 15, in run_webserver
    socketio.run(app, host= '0.0.0.0')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/pywsgi.py", line 1488, in init_socket
    self.update_environ()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/pywsgi.py", line 1500, in update_environ
    name = socket.getfqdn(address[0])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/_socketcommon.py", line 250, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/_socketcommon.py", line 222, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/resolver/thread.py", line 68, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 324, in gevent._event.AsyncResult.exc_info.__get__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
```
并且 `localhost:5000` 无法访问。
`localhost:8002`, `localhost:27017` 均正常。

**Comment by GarbageSal** [comment]
已解决
