### ISSUE TITLE
部署阶段访问 http://localhost:5000/ 时出现 jinja2.exceptions.TemplateNotFound: index/index.html

### ISSUE THREAD

**Issue by leelijin** [wonderfulsuccess/weixin_crawler#3]
执行以下命令启python5000端口，访问http://localhost:5000/ 时，报下面的错，该怎么修改flask的配置？
目录结构无更改，直接git clone下来的。

```
$ python project/main.py

09 15:44:37 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lijin/weixin_crawler/project/ui/router.py", line 6, in index
    return render_template('index/index.html', data={'title':'公众号采集'})
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/lijin/anaconda3/envs/weixin_crawler/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index/index.html
```
尝试过：
1. 修改 project/ui/ui_instance.py 中路径为绝对路径，依然无效；
```
app = CustomFlask('WeixinCrawler',template_folder="./ui/templates",static_folder="./ui/static")
```

2. 在 project/ui/ui_instance.py 中 添加 bootstrap = Bootstrap(app), 依然无效；

3. 把templates cp 到 项目根目录下，依然无效；

**Comment by wonderfulsuccess** [comment]
the error means jinja2 can not find the template file, you should $ python ./main.py inside project folder  but $ python project/main.py

**Comment by leelijin** [comment]
It fix my problem perfectly! 
thank u !
